## Iniciando com NumPy

In [1]:
import numpy as np

# Array unidimensional
arr = np.array([1, 2, 3])

# Array bidimensional
mtz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print(mtz)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Sobre o NumPy Array

O ndarray (NumPy Array) é a estrutura de dados fundamental do NumPy

O NumPy Array guarda apenas elementos do mesmo tipo:
  * Isso fornece maior desempenho nas operações 
  * Menor uso de memória



## Criando NumPy Arrays com mais facilidade

In [12]:
# Estruturando rapidamente uma matriz de 1's
mtz = np.ones([5, 5])
print(mtz)

# Estruturando um array de 0's
arr = np.zeros([10])
print(arr)

# Arange
mtz = np.arange(10)
print(mtz)

arr = np.arange(10, 31, 2)
print(arr)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3 4 5 6 7 8 9]
[10 12 14 16 18 20 22 24 26 28 30]


## Operações básicas com Array

In [20]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

print(arr1.min(), arr1.max())
print(arr1.argmin(), arr1.argmax()) # index

print(arr1.mean()) # media
print(arr1.sum())


arr3 = arr1 + arr1
print(arr3)
arr3 = arr1 * arr2
print(arr3)

print(np.concatenate([arr1, arr2]))

1 4
0 3
2.5
10
[2 4 6 8]
[ 5 12 21 32]
[1 2 3 4 5 6 7 8]


## Reshape de Numpy Arrays

In [26]:
mtz = np.arange(9).reshape(3, 3)
print(mtz)

# Propriedades da matriz
print(mtz.size, mtz.shape, mtz.ndim)

# Operações nas linhas e colunas da matriz
print(mtz.sum(axis=0)[0]) # colunas
print(mtz.sum(axis=1)) #linhas

[[0 1 2]
 [3 4 5]
 [6 7 8]]
9 (3, 3) 2
9
21


## Broadcasting

In [28]:
print(mtz/2)
print(mtz + mtz*0.2) # aumento de 20% em cada celula da matriz

[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
[[0.  1.2 2.4]
 [3.6 4.8 6. ]
 [7.2 8.4 9.6]]


## Elementos Aleatórios e únicos com arrays

In [35]:
# Gerando 10 números aleatórios
np.random.seed(10)
mtz = np.random.randint(20, 50, [5, 5])
print(mtz)

# Extraindo elementos unicos com unique
print(np.unique(mtz, return_counts=True))

[[29 49 24 35 20]
 [37 47 48 45 49]
 [36 49 37 46 28]
 [29 20 30 28 42]
 [24 39 36 24 35]]
(array([20, 24, 28, 29, 30, 35, 36, 37, 39, 42, 45, 46, 47, 48, 49]), array([2, 3, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1, 3]))


## Sliceing de Numpy Arrays (BIDIMENSIONAIS)

In [ ]:
mtz = np.arange(1, 10, 1).reshape(3, 3)
print(mtz)

# Slicing em uma unica linha
print(mtz[2])

# Slicing de multiplas linhas
print(mtz[1:])

# Slicing de uma coluna
print(mtz[:, 1])

# Slicing de multiplas colunas
print(mtz[:, 1:]) 

[2 5 8]
[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


## Condicionais

In [31]:
print(mtz > 5) # Mask de true ou false

print(mtz[mtz > 5])

print(mtz[mtz%2 == 0])

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]
[2 4 6 8]


## Trabalhando com Padrões Textuais

  * O subpacote **numpy.char** fornece um conjunto de operações para serem realizadas em elementos do tipo texto

In [ ]:
arr = np.array(['Goku', 'Gohan', 'Bulma', 'Vegeta', 'Goten', 'Androide 18'])

print(arr[np.char.find(arr, 'Go') >= 0])
print(np.char.find(arr, 'a')) # index
print(arr[np.char.find(arr, 'a') != -1])

print(arr[np.char.startswith(arr, 'Go')])
print(np.char.upper(arr), np.char.lower(arr))
print(arr[~(np.char.isalpha(arr))]) # Os que nao sao alpha (~ é inversão)

['Goku' 'Gohan' 'Goten']
[-1  3  4  5 -1 -1]
['Gohan' 'Bulma' 'Vegeta']
['Goku' 'Gohan' 'Goten']
['GOKU' 'GOHAN' 'BULMA' 'VEGETA' 'GOTEN' 'ANDROIDE 18'] ['goku' 'gohan' 'bulma' 'vegeta' 'goten' 'androide 18']
['Androide 18']


## Salvando e carregando dados com NumPy

In [51]:
dataset = np.loadtxt(
  './space.csv',
  delimiter=';',
  dtype='str',
  encoding='utf-8'
)

print(dataset[1, :])

['0' 'SpaceX' 'LC-39A Kennedy Space Center Florida USA'
 'Fri Aug 07 2020 05:12 UTC'
 'Falcon 9 Block 5 | Starlink V1 L9 & BlackSky' 'StatusActive' '50.0 '
 'Success']
